lastt

diff --git a/kriteria3/.github/workflows/main.yaml b/kriteria3/.github/workflows/main.yaml
--- a/kriteria3/.github/workflows/main.yaml
+++ b/kriteria3/.github/workflows/main.yaml
@@ -1,14 +1,17 @@
-name: CI Workflow
+name: CI Workflow - Alisha 
 
 on:
   push:
     branches: ["main"]
+    paths:
+      - 'kriteria3/**'
+      - '.github/workflows/**'
 
 permissions:
   contents: write 
 
 jobs:
-  build:
+  build_and_deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -18,34 +21,31 @@ jobs:
     - name: Setup python
       uses: actions/setup-python@v4
       with:
-        python-version: "3.12.7"
+        python-version: "3.12"
 
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install mlflow
+        pip install mlflow pandas scikit-learn numpy joblib dagshub
 
     - name: Run mlflow project
       run: |
-        mlflow run MLProject --env-manager=local
+        mlflow run kriteria3/MLProject --env-manager=local
 
-    - name: Get latest MLflow run_id
+    - name: Find Model Path
       run: |
-        RUN_ID=$(ls -td mlruns/0/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
-        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
-        echo "Latest run_id: $RUN_ID"
+        # Cari path folder model di dalam mlruns (di kedalaman mana pun)
+        MODEL_PATH=$(find mlruns -name "model" -type d | head -n 1)
+        
+        # Cek apakah ketemu
+        if [ -z "$MODEL_PATH" ]; then
+          echo "Error: Model tidak ditemukan!"
+          exit 1
+        fi
 
-    - name: Commit & Push results
-      run: |
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git add mlruns/
-        git commit -m "Upload artifact [skip ci]" || echo "No changes to commit"
-        git push origin main
+        echo "Model ditemukan di: $MODEL_PATH"
+        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
 
-    - name: Build Docker Model
-      run: |
-        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "insurance_model" 
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
@@ -53,10 +53,11 @@ jobs:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-    - name: Tag Docker Image
+    - name: Build Docker Model
+      run: |
+        mlflow models build-docker --model-uri "$MODEL_PATH" --name "insurance_model" 
+
+    - name: Tag & Push Docker Image
       run: |
         docker tag insurance_model ${{ secrets.DOCKER_HUB_USERNAME }}/insurance_model:latest
-        
-    - name: Push Docker Image
-      run: |
         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/insurance_model:latest
